name: Build and Push
on:
  push:
    branches: [main]
    paths-ignore:
      - "helm/**"
      - "*.md"

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker CLI
        run: |
          apt-get update && apt-get install -y docker.io
      - name: Login to Harbor
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASS: ${{ secrets.HARBOR_PASSWORD }}
        run: echo "$HARBOR_PASS" | docker login registry.home.lab -u "$HARBOR_USER" --password-stdin
      - name: Build and push API
        run: |
          docker build -t registry.home.lab/csgit34/corpocache-api:${{ github.sha }} -t registry.home.lab/csgit34/corpocache-api:latest -f Dockerfile.api .
          docker push registry.home.lab/csgit34/corpocache-api:${{ github.sha }}
          docker push registry.home.lab/csgit34/corpocache-api:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker CLI
        run: |
          apt-get update && apt-get install -y docker.io
      - name: Login to Harbor
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASS: ${{ secrets.HARBOR_PASSWORD }}
        run: echo "$HARBOR_PASS" | docker login registry.home.lab -u "$HARBOR_USER" --password-stdin
      - name: Build and push frontend
        run: |
          docker build -t registry.home.lab/csgit34/corpocache-frontend:${{ github.sha }} -t registry.home.lab/csgit34/corpocache-frontend:latest -f Dockerfile.frontend .
          docker push registry.home.lab/csgit34/corpocache-frontend:${{ github.sha }}
          docker push registry.home.lab/csgit34/corpocache-frontend:latest
