apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corpocache.fullname" . }}-config
  labels:
    {{- include "corpocache.api.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  PORT: "3000"
  PG_HOST: {{ .Values.database.host | quote }}
  PG_PORT: {{ .Values.database.port | quote }}
  PG_DATABASE: {{ .Values.database.name | quote }}
