{{- if not .Values.database.externalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corpocache.fullname" . }}-secret
  labels:
    {{- include "corpocache.api.labels" . | nindent 4 }}
type: Opaque
stringData:
  PG_USER: {{ .Values.database.user | quote }}
  PG_PASSWORD: {{ .Values.database.password | quote }}
  DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
{{- end }}
